### ISSUE TITLE
Escape : ?

### ISSUE THREAD

**Issue by bodiam** [tiagobento/watertemplate-engine#10]
Hi guys,

Is it possible to escape the : ? I have a water template like this:

````
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
````

And water doesn't like it, because of the : after https. How do I fix this?

**Comment by tiagobento** [comment]
Hi bodiam,

Which version of Water do you have? I've solved this issue in version 1.2.0.

Tiago

**Comment by bodiam** [comment]
Hi @tiagobento ,

I'm using a dependency on 'com.sparkjava:spark-template-water:1.0.0', from which I receive a transitive dependency on 1.1.0. When I change it to this:

    compile ('com.sparkjava:spark-template-water:1.0.0') {
        exclude module: 'watertemplate-engine'
    }
    compile 'org.watertemplate:watertemplate-engine:1.2.0'

It works. Thanks for the reply!

**Comment by tiagobento** [comment]
Dear @bodiam,

That's the only solution at the moment. As you saw, I've already made a pull request to spark-template-engines. Let's wait until they merge and release a new version.

I'm glad it worked. Any further problems please let me know.
