### ISSUE TITLE
"Booleans should not be evaluated"

### ISSUE THREAD

**Issue by CK9a5ISZ** [tiagobento/watertemplate-engine#17]
boolean found = true;

        add("found", found);

Causes 
`Caused by: org.watertemplate.exception.InvalidTemplateObjectEvaluationException: Booleans should not be evaluated
`

How am I supposted to use booleans then?
I want to make a simple if in the template for displaying list when results are found or displaying a nicely formatted message when they're not.

**Comment by tiagobento** [comment]
@CK9a5ISZ You must call .toString() on `found` so it's explicit that you're using this boolean as a String, and not as a condition. In this case, as it's a primitive boolean, you can use `Boolean.toString(found)` or even `found + ""`
