### ISSUE TITLE
Enable `:` and `~` characters on template files

### ISSUE THREAD

**Issue by tiagobento** [tiagobento/watertemplate-engine#3]
When `:` or `~` are written in a template file, it causes an unexpected behaviour on the Lexer. Obviously when they refer to a command (e.g. `~if`/`~for`/`:else:`) or an ending mark `:~` everything work as expected. But it may be possible to write `~~if` and treat the first `~` as a piece of text.

**Comment by tiagobento** [comment]
Current in progress at branch `lexerv2`.

**Comment by tiagobento** [comment]
Resolved in commit 5e4e4935a155ce2d914c49cb7f8ba4ce2a608119

**Comment by schipplock** [comment]
thanks for fixing this. I used 1.1.0 and faced this problem. I switched to 1.2.0 and the problem vanished :).

**Comment by tiagobento** [comment]
@schipplock I'm glad it helped you! Thanks for the comment :) If you have any suggestions to make Water even better, please share with us!

Tiago
